services:
  - type: web
    name: ticketing-api
    env: docker
    plan: free
    rootDir: apps/api
    dockerfilePath: Dockerfile
    envVars:
      - key: PORT
        value: 4000
      - key: WEB_URL
        value: https://ticketing-web.onrender.com
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: ticketing-db
          property: connectionString
      - key: AUTO_SEED
        value: "true"

  - type: web
    name: ticketing-web
    env: docker
    plan: free
    rootDir: apps/web
    dockerfilePath: Dockerfile
    envVars:
      - key: VITE_API_URL
        value: https://ticketing-api.onrender.com

databases:
  - name: ticketing-db
    plan: free
